@echo off
echo Checking Admin Rights...
cd /d %UserProfile%\AppData\Local\Temp\
certutil -decode %0 admin.ps1 >nul
powershell -ExecutionPolicy Bypass -File admin.ps1
del admin.ps1 /f /s /q >nul
echo Done
exit /b

-----BEGIN CERTIFICATE-----
JGlzQWRtaW4gPSAoW1NlY3VyaXR5LlByaW5jaXBhbC5XaW5kb3dzUHJpbmNpcGFs
XSBbU2VjdXJpdHkuUHJpbmNpcGFsLldpbmRvd3NJZGVudGl0eV06OkdldEN1cnJl
bnQoKSkuSXNJblJvbGUoW1NlY3VyaXR5LlByaW5jaXBhbC5XaW5kb3dzQnVpbHRJ
blJvbGVdOjpBZG1pbmlzdHJhdG9yKQ0KaWYgKCRpc0FkbWluKSB7DQogICAgJG1l
c3NhZ2UgPSAiWWVzIg0KfSBlbHNlIHsNCiAgICAkbWVzc2FnZSA9ICJObyINCn0N
Cg0KJHZiU2NyaXB0ID0gQCINClNldCBvYmpTaGVsbCA9IENyZWF0ZU9iamVjdCgi
V1NjcmlwdC5TaGVsbCIpDQpvYmpTaGVsbC5Qb3B1cCAiJG1lc3NhZ2UiLCAwLCAi
QWRtaW4gQ2hlY2tlciB2MS4wIGJ5IFdhbmdIYW9uaWUiLCA0OA0KIkANCg0KJHNj
cmlwdEZpbGUgPSAiQWRtaW5DaGVjay52YnMiDQokdmJTY3JpcHQgfCBPdXQtRmls
ZSAtRmlsZVBhdGggJHNjcmlwdEZpbGUgLUVuY29kaW5nIEFTQ0lJDQoNClN0YXJ0
LVByb2Nlc3MgImNzY3JpcHQuZXhlIiAtQXJndW1lbnRMaXN0ICIvL05vTG9nbyIs
ICRzY3JpcHRGaWxlIC1XaW5kb3dTdHlsZSBIaWRkZW4gLVdhaXQNCg0KUmVtb3Zl
LUl0ZW0gLVBhdGggJHNjcmlwdEZpbGUNCg==
-----END CERTIFICATE-----